# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='copies',
            field=models.IntegerField(),
        ),
    ]
